<?php

namespace app\index\controller;

use think\Controller;

class Base extends Controller
{
    //初始化
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->isLogin();
    }

    //判断是否登录
    public function isLogin()
    {
        if(empty(session('user_id'))){
            $this->error('还无登录,请先登录!','login/index');
        }
    }
}
